import type { Metadata } from "next";
import { Card, Container, PageHero } from "@/components/ui";

export const metadata: Metadata = { title: "Rules", description: "The core rules and roleplay standards of NorthBridge RP." };
const groups = [
  ["respect", "Respect Everyone", ["Treat every player with dignity, including during conflict.", "Harassment, discrimination, slurs, or targeted toxicity are prohibited."]],
  ["serious-rp", "Serious RP Only", ["Stay in character and give others meaningful opportunities to respond.", "Use believable character motivations; avoid trolling or scene-breaking behavior."]],
  ["rdm-vdm", "No RDM or VDM", ["Do not attack without valid roleplay initiation and escalation.", "Vehicles are not weapons except in an immediate, believable life-threatening circumstance."]],
  ["fear-rp", "Value Your Life / FearRP", ["React to danger as a real person would and prioritize your character’s survival.", "Do not force impossible heroics when clearly outmatched or restrained."]],
  ["metagaming", "No Metagaming", ["Only act on information your character learned in roleplay.", "Streams, Discord, and out-of-character conversations cannot inform in-city decisions."]],
  ["powergaming", "No Powergaming", ["Do not force outcomes, exploit mechanics, or deny another player a fair response.", "Use systems and emotes to support scenes—not to bypass consent or believable limits."]],
  ["new-life", "New Life Rule", ["After respawning, forget the immediate events leading to incapacitation.", "Do not return to an active scene to retaliate or recover property unless staff directs otherwise."]],
  ["safe-zones", "Safe Zones", ["Do not initiate criminal activity in designated protected areas.", "Safe zones never excuse fleeing into one to avoid an already active scene."]],
  ["cheating", "Exploiting & Cheating", ["Cheats, injected tools, duping, and intentional exploitation result in severe action.", "Report vulnerabilities privately; never demonstrate or distribute an exploit."]],
  ["combat-logging", "Combat Logging", ["Do not disconnect to avoid an interaction, consequence, arrest, or loss.", "If you crash, communicate promptly and make a good-faith effort to return."]],
  ["services", "Police & EMS", ["Allow public-service players to develop scenes and follow reasonable instructions.", "Corruption and extreme misconduct require prior staff approval where Discord rules specify it."]],
  ["crime", "Gang & Criminal RP", ["Build conflict through story, escalation, and clear motives—not constant gunplay.", "Follow current limits for groups, robberies, wars, and cooldowns in Discord."]],
  ["voice", "Voice & Microphone", ["A working, understandable microphone is required.", "Keep voice communication free of disruptive soundboards, distortion, and excessive background noise."]],
  ["staff", "Staff Decisions & Appeals", ["Follow staff direction during an active situation and discuss concerns afterward.", "Use the official ticket or appeal process; do not argue cases in public channels."]],
] as const;

export default function Rules() {
  return <><PageHero eyebrow="Community standards" title="Serious stories need shared rules." copy="These concise standards protect fair scenes, immersive characters, and a welcoming 18+ community."/><section className="py-16"><Container><div className="mb-10 rounded-lg border border-amber-400/25 bg-amber-400/10 p-5 text-sm leading-6 text-amber-100"><strong>Important:</strong> The full rules published in NorthBridge Discord remain authoritative until all website wording is finalized. Cheating, exploiting, harassment, and ban evasion are major violations.</div><div className="grid items-start gap-8 lg:grid-cols-[240px_1fr]"><aside className="glass sticky top-28 hidden max-h-[calc(100vh-8rem)] overflow-y-auto rounded-[var(--radius-card)] p-4 lg:block"><p className="eyebrow mb-3 px-2">Categories</p><nav aria-label="Rule categories" className="space-y-1">{groups.map(([id,title])=><a className="block rounded px-2 py-2 text-xs text-zinc-400 transition hover:bg-white/5 hover:text-white" href={`#${id}`} key={id}>{title}</a>)}</nav></aside><div><nav aria-label="Rule categories" className="mb-8 flex flex-wrap gap-2 lg:hidden">{groups.map(([id,title])=><a className="rounded border border-white/10 bg-white/5 px-3 py-2 text-xs text-zinc-300" href={`#${id}`} key={id}>{title}</a>)}</nav><div className="grid gap-5 xl:grid-cols-2">{groups.map(([id,title,rules],groupIndex)=><Card key={id} className="scroll-mt-28"><section id={id} className="scroll-mt-28"><p className="eyebrow">Category {String(groupIndex+1).padStart(2,"0")}</p><h2 className="mt-3 text-2xl font-black">{title}</h2><ol className="mt-5 space-y-3">{rules.map((rule,i)=><li className="flex gap-3 text-sm leading-6 text-zinc-400" key={rule}><span className="font-mono text-red-400">{i+1}.</span>{rule}</li>)}</ol></section></Card>)}</div></div></div></Container></section></>;
}
