import Image from "next/image"; import { BusinessCard } from "@/components/cards"; import { ServerStatus } from "@/components/server-status"; import { Button, Card, Container, SectionHeading } from "@/components/ui"; import { VideoHero } from "@/components/video-hero"; import { siteConfig } from "@/config/site"; import { businesses, departments, features, updates } from "@/data/content";
export default function Home() { return <>
  <VideoHero/>
  <section id="discover" className="relative -mt-20 pb-8"><Container><ServerStatus/></Container></section>
  <section className="section-space"><Container><SectionHeading eyebrow="Built differently" title="A city with depth." copy="Every system exists to support memorable characters, meaningful conflict, and long-term progression."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{features.map(([title,copy],i)=><Card key={title}><span className="font-mono text-sm text-red-400">0{i+1}</span><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 leading-6 text-zinc-400">{copy}</p></Card>)}</div></Container></section>
  <section className="border-y border-white/5 bg-white/[.015] py-24"><Container><SectionHeading eyebrow="The city economy" title="Businesses with identity." copy="Meet the first names shaping commerce, culture, and everyday life across NorthBridge."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{businesses.map(b=><BusinessCard business={b} key={b.name}/>)}</div><Card className="mt-5 text-center"><p className="eyebrow">More coming soon</p><p className="mt-2 text-zinc-400">The next great NorthBridge business could be yours.</p></Card></Container></section>
  <section className="py-24"><Container><SectionHeading eyebrow="Serve the city" title="Departments that create stories."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{departments.map(d=><Card key={d.short}><span className="eyebrow">{d.short}</span><h3 className="mt-4 text-xl font-black">{d.name}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{d.description}</p></Card>)}</div></Container></section>
  <section className="border-y border-white/5 bg-white/[.015] py-24"><Container><div className="flex items-end justify-between gap-6"><SectionHeading eyebrow="From the city" title="NorthBridge in motion."/><Button href="/gallery" variant="ghost">Full gallery</Button></div><div className="grid auto-rows-[240px] gap-4 md:grid-cols-3">{["city","events","vehicles"].map((name,i)=><div className={`relative overflow-hidden rounded-[var(--radius-card)] border border-white/10 ${i===0?"md:col-span-2":""}`} key={name}><Image src={`/images/gallery/${name}.svg`} alt={`${name} gallery preview`} fill className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><p className="absolute bottom-5 left-5 text-sm font-bold uppercase tracking-[.18em]">{name}</p></div>)}</div></Container></section>
  <section className="py-24"><Container><SectionHeading eyebrow="Development log" title="Latest updates." copy="A transparent look at the platform, community, and city roadmap."/><div className="grid gap-4 md:grid-cols-3">{updates.map(update=><Card key={update.title}><div className="flex items-center justify-between text-xs"><span className="eyebrow">{update.category}</span><span className="text-zinc-600">{update.date}</span></div><h3 className="mt-6 text-xl font-black">{update.title}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{update.copy}</p></Card>)}</div></Container></section>
  <section className="pb-24"><Container><div className="red-glow overflow-hidden rounded-xl border border-red-500/20 bg-[radial-gradient(circle_at_top_right,#a7193040,transparent_45%),#111114] p-8 sm:p-14"><SectionHeading eyebrow="Your next chapter" title="The bridge is open." copy="Meet the community, learn the standards, and start building your character."/><div className="flex flex-wrap gap-3"><Button href={siteConfig.discordUrl}>Join Discord</Button><Button href="/join" variant="secondary">Join NorthBridge</Button><Button href="/departments" variant="ghost">Apply for a department</Button><Button href="/rules" variant="ghost">View rules</Button></div></div></Container></section>
 </>; }
