import Image from "next/image"; import { BusinessCard } from "@/components/cards"; import { ServerStatus } from "@/components/server-status"; import { Button, Card, Container, SectionHeading } from "@/components/ui"; import { siteConfig } from "@/config/site"; import { businesses, departments, features } from "@/data/content";
export default function Home() { return <>
  <section className="relative flex min-h-screen items-center overflow-hidden"><Image src="/images/hero/city.svg" alt="Abstract NorthBridge city skyline placeholder" fill priority className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#070708_5%,#070708dd_48%,#07070866),linear-gradient(0deg,#070708_0%,transparent_45%)]"/><Container className="relative pb-20 pt-32"><div className="reveal max-w-4xl"><p className="eyebrow mb-5">18+ serious roleplay · Qbox</p><h1 className="text-gradient text-6xl font-black leading-[.88] tracking-[-.06em] sm:text-8xl lg:text-[7rem]">NORTHBRIDGE<br/>RP</h1><p className="mt-6 text-xl font-bold tracking-wide sm:text-2xl">Your Story. Your City. Your Legacy.</p><p className="mt-5 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">A cinematic, player-driven FiveM experience where serious roleplay, custom systems, and an invested community create stories worth remembering.</p><div className="mt-8 flex flex-wrap gap-3"><Button href={siteConfig.connectUrl}>Join Server</Button><Button href={siteConfig.discordUrl} variant="secondary">Discord</Button><Button href={siteConfig.storeUrl} variant="ghost">Store</Button></div></div></Container></section>
  <section className="relative -mt-24 pb-24"><Container><ServerStatus/></Container></section>
  <section className="py-24"><Container><SectionHeading eyebrow="Built differently" title="A city with depth." copy="Every system exists to support memorable characters, meaningful conflict, and long-term progression."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([title,copy],i)=><Card key={title}><span className="font-mono text-sm text-red-400">0{i+1}</span><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 leading-6 text-zinc-400">{copy}</p></Card>)}</div></Container></section>
  <section className="border-y border-white/5 bg-white/[.015] py-24"><Container><SectionHeading eyebrow="The city economy" title="Businesses with identity." copy="Meet the first names shaping commerce, culture, and everyday life across NorthBridge."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{businesses.map(b=><BusinessCard business={b} key={b.name}/>)}</div><Card className="mt-5 text-center"><p className="eyebrow">More coming soon</p><p className="mt-2 text-zinc-400">The next great NorthBridge business could be yours.</p></Card></Container></section>
  <section className="py-24"><Container><SectionHeading eyebrow="Serve the city" title="Departments that create stories."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{departments.map(d=><Card key={d.short}><span className="eyebrow">{d.short}</span><h3 className="mt-4 text-xl font-black">{d.name}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{d.description}</p></Card>)}</div></Container></section>
  <section className="pb-24"><Container><div className="red-glow overflow-hidden rounded-xl border border-red-500/20 bg-[radial-gradient(circle_at_top_right,#a7193040,transparent_45%),#111114] p-8 sm:p-14"><SectionHeading eyebrow="Your next chapter" title="The bridge is open." copy="Meet the community, learn the standards, and start building your character."/><div className="flex flex-wrap gap-3"><Button href={siteConfig.discordUrl}>Join Discord</Button><Button href="/join" variant="secondary">Join NorthBridge</Button><Button href="/departments" variant="ghost">Apply for a department</Button><Button href="/rules" variant="ghost">View rules</Button></div></div></Container></section>
 </>; }
