import Link from "next/link";
import type { ReactNode } from "react";

export function Container({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`mx-auto w-full max-w-7xl px-5 sm:px-8 ${className}`}>{children}</div>; }
export function Button({ href, children, variant = "primary", size = "md", className = "" }: { href: string; children: ReactNode; variant?: "primary" | "secondary" | "ghost"; size?: "sm" | "md" | "lg"; className?: string }) {
  const styles = variant === "primary" ? "bg-[#b51224] hover:bg-[#d31f34] border-[#e02b3f] shadow-[0_10px_35px_#b5122430]" : variant === "secondary" ? "bg-white/8 hover:bg-white/14 border-white/15" : "bg-transparent hover:bg-white/5 border-white/10";
  const sizes = size === "lg" ? "min-h-13 px-7 py-3 text-sm" : size === "sm" ? "min-h-9 px-4 py-2 text-xs" : "min-h-11 px-5 py-2.5 text-sm";
  const classes = `inline-flex items-center justify-center rounded-[var(--radius-control)] border font-bold uppercase tracking-[.1em] transition duration-200 hover:-translate-y-0.5 active:translate-y-0 ${sizes} ${styles} ${className}`;
  return href.startsWith("/") ? <Link className={classes} href={href}>{children}</Link> : <a className={classes} href={href} target="_blank" rel="noreferrer">{children}</a>;
}
export function Badge({ children, tone = "accent" }: { children: ReactNode; tone?: "accent" | "success" | "neutral" }) { const toneClass = tone === "success" ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-300" : tone === "neutral" ? "border-white/15 bg-white/5 text-zinc-300" : "border-red-500/25 bg-red-500/10 text-red-300"; return <span className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-bold ${toneClass}`}>{children}</span>; }
export function Card({ children, className = "", interactive = true }: { children: ReactNode; className?: string; interactive?: boolean }) { return <div className={`glass rounded-[var(--radius-card)] p-6 transition duration-300 ${interactive ? "hover:-translate-y-1 hover:border-red-500/25" : ""} ${className}`}>{children}</div>; }
export function SectionHeading({ eyebrow, title, copy, center = false }: { eyebrow: string; title: string; copy?: string; center?: boolean }) { return <div className={`mb-10 max-w-3xl ${center ? "mx-auto text-center" : ""}`}><p className="eyebrow mb-3">{eyebrow}</p><h2 className="text-3xl font-black tracking-tight sm:text-5xl">{title}</h2>{copy && <p className="mt-4 text-base leading-7 text-zinc-400 sm:text-lg">{copy}</p>}</div>; }
export function PageHero({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <section className="relative overflow-hidden border-b border-white/5 pb-20 pt-36"><div className="absolute inset-0 grid-lines opacity-20" /><Container className="relative"><p className="eyebrow mb-4">{eyebrow}</p><h1 className="max-w-4xl text-5xl font-black tracking-[-.04em] sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">{copy}</p></Container></section>; }
